image: Visual Studio 2017
configuration: Release

environment:
  assemblyVersion: 2.0.0
  access_token:
    secure: IlfmHXRdUK6v8dX/WqieXQ==
  testfilter: TestCategory != FreeText & TestCategory != Explicit
  #testFilter: TestCategory=Create
  testRunner: dotnet
  testLogger: trx
  testConfiguration: AppVeyor
  matrix:
    - target: Default
      testTargetFramework: net452
    - target: Tests
      testTargetFramework: netcoreapp1.0
      testFilter: TestCategory=Create
    - target: Tests
      testTargetFramework: netcoreapp2.0
      testFilter: TestCategory=Create
    - target: DocFx

cache:
- packages -> appveyor.yml

version: $(assemblyVersion).{build}

services:
- mssql2014
- mysql
- postgresql95

init:
- cmd: git config --global core.autocrlf true
- ps: $env:buildVersion = "$env:assemblyVersion.$env:appveyor_build_number"

nuget:
  account_feed: false
  project_feed: false

build_script:
  #msbuild linq2db.sln /p:Configuration=AppVeyor /t:Restore;Build /v:m
- ps: |
    $env:packageVersion = $env:assemblyVersion
    if ($env:APPVEYOR_REPO_BRANCH -ne "release") 
    {
        $env:packageVersion = "$env:assemblyVersion-rc$env:appveyor_build_number"
    }

    .\Build\CodeJam.AppVeyor.FixVersionProps.ps1 -path Build\linq2db.Default.props -buildVersion $env:assemblyVersion -nugetVersion $env:packageVersion
- ps: .\build.ps1

before_build:
- ps: |
    $startPath = "$($env:appveyor_build_folder)\Data"
    $sqlInstance = "(local)\SQL2014"
    $dbName = "TestData"

    # create database
    sqlcmd -S "$sqlInstance" -Q "Use [master]; CREATE DATABASE [$dbName]"

    # MySql
    $env:MYSQL_PWD="Password12!"
    $cmd = '"C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "create database $dbName;" --user=root'
    iex "& $cmd"

    # PgSql
    $env:PGUSER="postgres"
    $env:PGPASSWORD="Password12!"
    $cmd = '"C:\Program Files\PostgreSQL\9.5\bin\createdb" $dbName'
    iex "& $cmd"
- ps: Update-AppveyorBuild -Version $env:buildVersion
- cmd: sqlcmd -U sa -P Password12! -S localhost\SQL2014 -i "Data\Create Scripts\Northwind.sql" > nul

test: off
  # only assemblies to test
  #assemblies:
  #  - Tests\Linq\**\linq2db.Tests.dll
  #categories:
  #  except:
  #    - FreeText

artifacts:
- path: \**\linq2db*.nupkg
- path: \**\*.trx

deploy:
- provider: NuGet
  server: https://www.myget.org/F/linq2db/api/v2
  api_key:
    secure: LDw0jeA1Yo3R4/TKv2kmlgJR8dTT6Wun2MONq3uDvtVQJG4LOU9LjvVTAc7IgRfm
  skip_symbols: true
  on:
    branch: master

- provider: NuGet
  api_key:
    secure: oTYw2IwTnz4qMD8c/MR/6mo+Nx3wa5Pp8MYfsKBCKCVuU6QCHlj+6QMXpnQses8G
  on:
    branch: release

- provider: NuGet
  server: https://www.myget.org/F/linq2db/api/v2
  api_key:
    secure: LDw0jeA1Yo3R4/TKv2kmlgJR8dTT6Wun2MONq3uDvtVQJG4LOU9LjvVTAc7IgRfm
  skip_symbols: true
  on:
    branch: release1

skip_commits:
  message: /ci skip/      # Regex for matching commit message
